import std/strformat
import ../avutil/version
import version_major

const
  LIBAVCODEC_VERSION_MINOR* = 31
  LIBAVCODEC_VERSION_MICRO* = 102
  LIBAVCODEC_VERSION_INT* = AV_VERSION_INT(LIBAVCODEC_VERSION_MAJOR,
      LIBAVCODEC_VERSION_MINOR, LIBAVCODEC_VERSION_MICRO)
  LIBAVCODEC_VERSION* = AV_VERSION(LIBAVCODEC_VERSION_MAJOR,
                                 LIBAVCODEC_VERSION_MINOR,
                                 LIBAVCODEC_VERSION_MICRO)
  LIBAVCODEC_BUILD* = LIBAVCODEC_VERSION_INT

# #define LIBAVCODEC_IDENT        "Lavc" AV_STRINGIFY(LIBAVCODEC_VERSION)
proc LIBAVCODEC_IDENT*():string =
  &"Lavc{LIBAVCODEC_VERSION}"