


const
  LIBAVCODEC_VERSION_MAJOR* = 61


const
  FF_API_INIT_PACKET* = (LIBAVCODEC_VERSION_MAJOR < 62)
  FF_API_SUBFRAMES* = (LIBAVCODEC_VERSION_MAJOR < 62)
  FF_API_TICKS_PER_FRAME* = (LIBAVCODEC_VERSION_MAJOR < 62)
  FF_API_DROPCHANGED* = (LIBAVCODEC_VERSION_MAJOR < 62)
  FF_API_AVFFT* = (LIBAVCODEC_VERSION_MAJOR < 62)
  FF_API_FF_PROFILE_LEVEL* = (LIBAVCODEC_VERSION_MAJOR < 62)
  FF_API_AVCODEC_CLOSE* = (LIBAVCODEC_VERSION_MAJOR < 62)
  FF_API_BUFFER_MIN_SIZE* = (LIBAVCODEC_VERSION_MAJOR < 62)
  FF_API_VDPAU_ALLOC_GET_SET* = (LIBAVCODEC_VERSION_MAJOR < 62)
  FF_API_QUALITY_FACTOR* = (LIBAVCODEC_VERSION_MAJOR < 62)
