import std/strformat

template AV_VERSION_INT*(a, b, c: untyped): untyped =
  ((a) shl 16 or (b) shl 8 or (c))

#-------
# #define AV_VERSION_DOT(a, b, c) a ##.## b ##.## c
proc AV_VERSION_DOT*(a, b, c: int): string {.inline.} =
  &"{a}.{b}.{c}"
#------


template AV_VERSION*(a, b, c: untyped): untyped =
  AV_VERSION_DOT(a, b, c)


template AV_VERSION_MAJOR*(a: untyped): untyped =
  ((a) shr 16)

template AV_VERSION_MINOR*(a: untyped): untyped =
  (((a) and 0x00FF00) shr 8)

template AV_VERSION_MICRO*(a: untyped): untyped =
  ((a) and 0xFF)


const
  LIBAVUTIL_VERSION_MAJOR* = 58
  LIBAVUTIL_VERSION_MINOR* = 29
  LIBAVUTIL_VERSION_MICRO* = 100
  LIBAVUTIL_VERSION_INT* = AV_VERSION_INT(LIBAVUTIL_VERSION_MAJOR,
                                        LIBAVUTIL_VERSION_MINOR,
                                        LIBAVUTIL_VERSION_MICRO)
  LIBAVUTIL_VERSION* = AV_VERSION(LIBAVUTIL_VERSION_MAJOR, LIBAVUTIL_VERSION_MINOR,
                                LIBAVUTIL_VERSION_MICRO)
  LIBAVUTIL_BUILD* = LIBAVUTIL_VERSION_INT



# #define LIBAVUTIL_IDENT         "Lavu" AV_STRINGIFY(LIBAVUTIL_VERSION)
proc LIBAVUTIL_IDENT*():string =
  &"Lavu{LIBAVUTIL_VERSION}"

const
  FF_API_FIFO_PEEK2* = (LIBAVUTIL_VERSION_MAJOR < 59)
  FF_API_FIFO_OLD_API* = (LIBAVUTIL_VERSION_MAJOR < 59)
  FF_API_XVMC* = (LIBAVUTIL_VERSION_MAJOR < 59)
  FF_API_OLD_CHANNEL_LAYOUT* = (LIBAVUTIL_VERSION_MAJOR < 59)
  FF_API_AV_FOPEN_UTF8* = (LIBAVUTIL_VERSION_MAJOR < 59)
  FF_API_PKT_DURATION* = (LIBAVUTIL_VERSION_MAJOR < 59)
  FF_API_REORDERED_OPAQUE* = (LIBAVUTIL_VERSION_MAJOR < 59)
  FF_API_FRAME_PICTURE_NUMBER* = (LIBAVUTIL_VERSION_MAJOR < 59)
  FF_API_HDR_VIVID_THREE_SPLINE* = (LIBAVUTIL_VERSION_MAJOR < 59)
  FF_API_FRAME_PKT* = (LIBAVUTIL_VERSION_MAJOR < 59)
  FF_API_INTERLACED_FRAME* = (LIBAVUTIL_VERSION_MAJOR < 59)
  FF_API_FRAME_KEY* = (LIBAVUTIL_VERSION_MAJOR < 59)
  FF_API_PALETTE_HAS_CHANGED* = (LIBAVUTIL_VERSION_MAJOR < 59)
  FF_API_VULKAN_CONTIGUOUS_MEMORY* = (LIBAVUTIL_VERSION_MAJOR < 59)

